version: 2

builds:
  -
    ldflags:
      - -s -w -X github.com/Selleo/cli/selleo.Version={{.Tag}}
    goarch:
      - amd64
      - arm64
    goarm:
      - "7"
    ignore:
      - goos: linux
        goarch: arm64

    tags:
      - prod

    env:
      - CGO_ENABLED=0

    binary: selleo

brews:
  - name: selleo
    repository:
      owner: Selleo
      name: homebrew-cli
      branch: main
      token: "{{ .Env.HOMEBREW_CLI_GITHUB_TOKEN }}"
    goarm: "7"
    directory: Formula
    homepage: https://github.com/selleo/cli
    description: Selleo's CLI for better developer experience.
    license: MIT
