builds:
  -
    ldflags:
      - -s -w -X github.com/Selleo/cli/selleo.Version={{.Tag}}
    goarch:
      - amd64
      - arm64
    goarm:
      - 7
    ignore:
      - goos: linux
        goarch: arm64

    tags:
      - prod

    binary: selleo
