name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Go
      - uses: actions/setup-go@v5
        with:
          go-version: '1.23.1' # The Go version to download (if necessary) and use.

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v6
        with:
          distribution: goreleaser
          version: '~> v2'
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_CLI_GITHUB_TOKEN: ${{ secrets.HOMEBREW_CLI_GITHUB_TOKEN }}
