name: Release

permissions:
  contents: write

on:
  push:
    tags:
      - '*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v3

      -
        name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.18

      -
        name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v2
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_CLI_GITHUB_TOKEN: ${{ secrets.HOMEBREW_CLI_GITHUB_TOKEN }}
